# Generated by Django 2.2.24 on 2021-08-31 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('published_date', models.DateField()),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ratings_count', models.SmallIntegerField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='http://books.google.com/books/<filename>/')),
                ('authors', models.ManyToManyField(to='books.Author')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Categories')),
            ],
        ),
    ]
