# Generated by Django 2.2.24 on 2021-09-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='surname',
        ),
    ]
