# Generated by Django 2.2.24 on 2021-09-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
