# Generated by Django 2.2.24 on 2021-09-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210903_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.SmallIntegerField(null=True),
        ),
    ]
