# Generated by Django 2.2.24 on 2021-09-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210904_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(max_length=500),
        ),
    ]
